-- Remover tabela antiga (se existir com estrutura diferente)
DROP TABLE IF EXISTS config;

-- Criar tabela se não existir
CREATE TABLE IF NOT EXISTS config (
    id bigint generated by default as identity primary key,
    type text not null,
    name text not null,
    color text,
    count int default 0,
    created_at timestamp with time zone default timezone('utc'::text, now())
);

-- Limpar tabela (Opcional, cuidado)
DELETE FROM config;

-- Inserir Categorias
INSERT INTO config (type, name, color) VALUES
('category', 'Alimentação & Bebidas', '#f59e0b'),
('category', 'Estrutura & Espaço', '#ec4899'),
('category', 'Experiência Geral', '#10b981'),
('category', 'Programação & Atrações', '#a855f7'),
('category', 'Credenciamento & Ingressos', '#3b82f6'),
('category', 'Segurança & Organização', '#10b981');

-- Inserir Regiões
INSERT INTO config (type, name) VALUES
('region', 'VIP & Camarotes'),
('region', 'Estacionamento'),
('region', 'Entrada Principal'),
('region', 'Área de Bares'),
('region', 'Área do Palco'),
('region', 'Praça de Alimentação'),
('region', 'Pista Central'),
('region', 'Banheiros'),
('region', 'Bistrô');
